### ISSUE TITLE
Container Restarts

### ISSUE THREAD

**Issue by jk0** [JrCs/docker-crashplan#23]
Have there been any thoughts on the `Synchronizing block information` that occurs after every container restart? This seems to happen even after committing the changes to the image when the synchronization is complete. I've made sure to mount the `/var/crashplan` volume. Is the block cache stored in a different directory?

**Comment by jk0** [comment]
According to this: https://support.code42.com/CrashPlan/4/Backup/CrashPlan_Cache_Files

It looks like the cache is indeed stored outside of `/var/crashplan`. I will test and confirm.

**Comment by jk0** [comment]
Mounting the `/usr/local/crashplan/cache` volume seems to make no difference.

**Comment by jk0** [comment]
Looks like the changes in `/usr/local/crashplan/cache` didn't persist after the restart. Trying again with a `commit`.

**Comment by jk0** [comment]
https://github.com/JrCs/docker-crashplan/blob/master/files/entrypoint.sh#L43

I'm having a hard time parsing what `_link()` does, but it looks like `/var/crashplan/cache` is not getting updated after the block synchronization completes, and is therefore overwriting `/usr/local/crashplan/cache` with old data every time the container starts.

**Comment by jk0** [comment]
I can confirm that even after manually copying the cache to `/var/crashplan/cache` that `/usr/local/crashplan/cache` continues to get overwritten with the image defaults, even after committing the changes.

**Comment by jk0** [comment]
@JrCs any suggestions?

**Comment by JrCs** [comment]
Thanks for the report, i will look at this issue.

**Comment by olines** [comment]
@JrCs  I am seeing the same issue. Thanks for looking into it...

**Comment by JrCs** [comment]
I have double check and it works as expected on my crashplan servers.
If you follow the readme, you must mount a directory containing all data for crashplan to the /var/crashplan. Example:

```
--volume /srv/crashplan/data:/var/crashplan
```

In /srv/crashplan/data you must find these directories:

```
bin  cache  conf  id  lang  lib  log
```

This is where persistant data are store.

**Comment by jk0** [comment]
As I mentioned above, I've mounted the `/var/crashplan` volume. The problem is that every time the container is restarted, this line kicks off: https://github.com/JrCs/docker-crashplan/blob/master/files/entrypoint.sh#L43

And overwrites the cache in `/var/crashplan/cache`, so it needs to re-sync the block information.

**Comment by JrCs** [comment]
No the line in the entrypoint.sh script only copy the files that are not present in the destination from /usr/local/crashplan/cache to /var/crashplan/cache (in the container point of view). In the container this directory is empty so nothing is copied and the /var/crashplan/cache doesn't change.
After the entrypont.sh have been executed the container must contain a link
/usr/local/crashplan/cache -> /var/crashplan/cache

**Comment by jk0** [comment]
Somehow the `/var/crashplan/cache` directory is getting overwritten with the image defaults after every restart. This happens even after committing the changes to the container after the block sync completes.

**Comment by JrCs** [comment]
Can you send me the docker run command you use ?

**Comment by jk0** [comment]
```
docker run -d \
  --name CrashPlan \
  -h $HOSTNAME \
  -p 4242:4242 -p 4243:4243 \
  -v /volume1/CrashPlan/var/crashplan:/var/crashplan \
  -v /volume1/Backup:/volume1/Backup:ro \
  jrcs/crashplan:latest
```

**Comment by JrCs** [comment]
Can you run this on your system:

``` bash
docker run -it --rm --entrypoint=bash \
-v /volume1/CrashPlan/var/crashplan:/var/crashplan \
-v /volume1/Backup:/volume1/Backup:ro \
jrcs/crashplan \
-c 'ls -ld /usr/local/crashplan/*; bash -x /entrypoint.sh ls -ld /usr/local/crashplan/* /var/crashplan/*'
```

and send me the ouput ?

**Comment by jk0** [comment]
```
-rw-r--r-- 1 root root       4 Oct  4 05:53 /usr/local/crashplan/CrashPlanEngine.pid
-rw-rw-r-- 1 root root 7639158 Oct  4 05:53 /usr/local/crashplan/app.asar
drwxrwxr-x 2 root root    4096 Oct  4 05:53 /usr/local/crashplan/bin
drwxrwxr-x 2 root root    4096 Oct  4 05:53 /usr/local/crashplan/conf
drwxrwxr-x 2 root root    4096 Oct  4 05:53 /usr/local/crashplan/doc
-rw-r--r-- 1 root root     428 Oct  4 05:53 /usr/local/crashplan/install.vars
drwxr-xr-x 5 root root    4096 Oct  4 05:53 /usr/local/crashplan/jre
drwxrwxr-x 2 root root    4096 Oct  4 05:53 /usr/local/crashplan/lang
drwxrwxr-x 2 root root    4096 Oct  4 05:53 /usr/local/crashplan/lib
-rw-rw-r-- 1 root root   11854 Oct  4 05:53 /usr/local/crashplan/libc42archive.so
-rw-rw-r-- 1 root root   13060 Oct  4 05:53 /usr/local/crashplan/libc42archive64.so
-rw-rw-r-- 1 root root   24756 Oct  4 05:53 /usr/local/crashplan/libjniwrap.so
-rw-rw-r-- 1 root root   48344 Oct  4 05:53 /usr/local/crashplan/libjniwrap64.so
-rw-rw-r-- 1 root root  257693 Oct  4 05:53 /usr/local/crashplan/libjtux.so
-rw-rw-r-- 1 root root  287934 Oct  4 05:53 /usr/local/crashplan/libjtux64.so
-rw-rw-r-- 1 root root  403970 Oct  4 05:53 /usr/local/crashplan/libleveldb.so
-rw-rw-r-- 1 root root  427599 Oct  4 05:53 /usr/local/crashplan/libleveldb64.so
-rw-rw-r-- 1 root root    7346 Oct  4 05:53 /usr/local/crashplan/libmd5.so
-rw-rw-r-- 1 root root    8417 Oct  4 05:53 /usr/local/crashplan/libmd564.so
drwxrwxr-x 3 root root    4096 Oct  4 05:53 /usr/local/crashplan/skin
drwxrwxr-x 3 root root    4096 Oct  4 05:53 /usr/local/crashplan/upgrade
+ [[ -n '' ]]
+ _link /var/crashplan/lib /usr/local/crashplan/lib
+ [[ -L /usr/local/crashplan/lib ]]
+ [[ ! -e /var/crashplan/lib ]]
+ [[ -d /usr/local/crashplan/lib ]]
+ rm -rf /usr/local/crashplan/lib
++ dirname /usr/local/crashplan/lib
+ [[ ! -d /usr/local/crashplan ]]
+ ln -sf /var/crashplan/lib /usr/local/crashplan/lib
+ _link /var/crashplan/lang /usr/local/crashplan/lang
+ [[ -L /usr/local/crashplan/lang ]]
+ [[ ! -e /var/crashplan/lang ]]
+ [[ -d /usr/local/crashplan/lang ]]
+ rm -rf /usr/local/crashplan/lang
++ dirname /usr/local/crashplan/lang
+ [[ ! -d /usr/local/crashplan ]]
+ ln -sf /var/crashplan/lang /usr/local/crashplan/lang
+ _link /var/crashplan/id /var/lib/crashplan
+ [[ -L /var/lib/crashplan ]]
+ [[ ! -e /var/crashplan/id ]]
+ [[ -d /var/lib/crashplan ]]
+ [[ -f /var/lib/crashplan ]]
+ [[ -L /var/lib/crashplan ]]
++ dirname /var/lib/crashplan
+ [[ ! -d /var/lib ]]
+ ln -sf /var/crashplan/id /var/lib/crashplan
+ _link /var/crashplan/cache /usr/local/crashplan/cache
+ [[ -L /usr/local/crashplan/cache ]]
+ [[ ! -e /var/crashplan/cache ]]
+ [[ -d /usr/local/crashplan/cache ]]
+ [[ -f /usr/local/crashplan/cache ]]
+ [[ -L /usr/local/crashplan/cache ]]
++ dirname /usr/local/crashplan/cache
+ [[ ! -d /usr/local/crashplan ]]
+ ln -sf /var/crashplan/cache /usr/local/crashplan/cache
+ _link /var/crashplan/log /usr/local/crashplan/log
+ [[ -L /usr/local/crashplan/log ]]
+ [[ ! -e /var/crashplan/log ]]
+ [[ -d /usr/local/crashplan/log ]]
+ [[ -f /usr/local/crashplan/log ]]
+ [[ -L /usr/local/crashplan/log ]]
++ dirname /usr/local/crashplan/log
+ [[ ! -d /usr/local/crashplan ]]
+ ln -sf /var/crashplan/log /usr/local/crashplan/log
+ [[ ! -f /var/crashplan/conf/default.service.xml ]]
+ _link /var/crashplan/conf /usr/local/crashplan/conf
+ [[ -L /usr/local/crashplan/conf ]]
+ [[ ! -e /var/crashplan/conf ]]
+ [[ -d /usr/local/crashplan/conf ]]
+ rm -rf /usr/local/crashplan/conf
++ dirname /usr/local/crashplan/conf
+ [[ ! -d /usr/local/crashplan ]]
+ ln -sf /var/crashplan/conf /usr/local/crashplan/conf
+ _link /var/crashplan/bin/run.conf /usr/local/crashplan/bin/run.conf
+ [[ -L /usr/local/crashplan/bin/run.conf ]]
+ [[ ! -e /var/crashplan/bin/run.conf ]]
+ [[ -d /usr/local/crashplan/bin/run.conf ]]
+ [[ -f /usr/local/crashplan/bin/run.conf ]]
+ rm -f /usr/local/crashplan/bin/run.conf
++ dirname /usr/local/crashplan/bin/run.conf
+ [[ ! -d /usr/local/crashplan/bin ]]
+ ln -sf /var/crashplan/bin/run.conf /usr/local/crashplan/bin/run.conf
+ TARGETDIR=/usr/local/crashplan
+ [[ -z '' ]]
+ PUBLIC_IP=0.0.0.0
+ PUBLIC_PORT=4242
+ [[ -f /usr/local/crashplan/conf/my.service.xml ]]
+ echo 'Configuring CrashPlan to listen on public interface 0.0.0.0:4242'
Configuring CrashPlan to listen on public interface 0.0.0.0:4242
+ sed -i -r 's/<location>[^<]+/<location>0.0.0.0:4242/g' /usr/local/crashplan/conf/my.service.xml
+ exec ls -ld /usr/local/crashplan/CrashPlanEngine.pid /usr/local/crashplan/app.asar /usr/local/crashplan/bin /usr/local/crashplan/conf /usr/local/crashplan/doc /usr/local/crashplan/install.vars /usr/local/crashplan/jre /usr/local/crashplan/lang /usr/local/crashplan/lib /usr/local/crashplan/libc42archive.so /usr/local/crashplan/libc42archive64.so /usr/local/crashplan/libjniwrap.so /usr/local/crashplan/libjniwrap64.so /usr/local/crashplan/libjtux.so /usr/local/crashplan/libjtux64.so /usr/local/crashplan/libleveldb.so /usr/local/crashplan/libleveldb64.so /usr/local/crashplan/libmd5.so /usr/local/crashplan/libmd564.so /usr/local/crashplan/skin /usr/local/crashplan/upgrade /var/crashplan/bin /var/crashplan/cache /var/crashplan/conf /var/crashplan/id /var/crashplan/lang /var/crashplan/lib /var/crashplan/log
-rw-r--r-- 1 root root       4 Oct  4 05:53 /usr/local/crashplan/CrashPlanEngine.pid
-rw-rw-r-- 1 root root 7639158 Oct  4 05:53 /usr/local/crashplan/app.asar
drwxrwxr-x 2 root root    4096 Oct 31 15:57 /usr/local/crashplan/bin
lrwxrwxrwx 1 root root      19 Oct 31 15:57 /usr/local/crashplan/conf -> /var/crashplan/conf
drwxrwxr-x 2 root root    4096 Oct  4 05:53 /usr/local/crashplan/doc
-rw-r--r-- 1 root root     428 Oct  4 05:53 /usr/local/crashplan/install.vars
drwxr-xr-x 5 root root    4096 Oct  4 05:53 /usr/local/crashplan/jre
lrwxrwxrwx 1 root root      19 Oct 31 15:57 /usr/local/crashplan/lang -> /var/crashplan/lang
lrwxrwxrwx 1 root root      18 Oct 31 15:57 /usr/local/crashplan/lib -> /var/crashplan/lib
-rw-rw-r-- 1 root root   11854 Oct  4 05:53 /usr/local/crashplan/libc42archive.so
-rw-rw-r-- 1 root root   13060 Oct  4 05:53 /usr/local/crashplan/libc42archive64.so
-rw-rw-r-- 1 root root   24756 Oct  4 05:53 /usr/local/crashplan/libjniwrap.so
-rw-rw-r-- 1 root root   48344 Oct  4 05:53 /usr/local/crashplan/libjniwrap64.so
-rw-rw-r-- 1 root root  257693 Oct  4 05:53 /usr/local/crashplan/libjtux.so
-rw-rw-r-- 1 root root  287934 Oct  4 05:53 /usr/local/crashplan/libjtux64.so
-rw-rw-r-- 1 root root  403970 Oct  4 05:53 /usr/local/crashplan/libleveldb.so
-rw-rw-r-- 1 root root  427599 Oct  4 05:53 /usr/local/crashplan/libleveldb64.so
-rw-rw-r-- 1 root root    7346 Oct  4 05:53 /usr/local/crashplan/libmd5.so
-rw-rw-r-- 1 root root    8417 Oct  4 05:53 /usr/local/crashplan/libmd564.so
drwxrwxr-x 3 root root    4096 Oct  4 05:53 /usr/local/crashplan/skin
drwxrwxr-x 3 root root    4096 Oct  4 05:53 /usr/local/crashplan/upgrade
drwxrwxrwx 2 root root    4096 Oct 19 19:42 /var/crashplan/bin
drwxrwxrwx 3 root root    4096 Oct 21 04:31 /var/crashplan/cache
drwxrwxr-x 3 root root    4096 Oct 31 15:57 /var/crashplan/conf
drwxrwxrwx 2 root root    4096 Oct 19 19:42 /var/crashplan/id
drwxrwxrwx 2 root root    4096 Oct 19 19:42 /var/crashplan/lang
drwxrwxrwx 2 root root    4096 Oct 19 19:42 /var/crashplan/lib
drwxrwxrwx 2 root root    4096 Oct 25 14:54 /var/crashplan/log
```

**Comment by JrCs** [comment]
Can you run this:

``` bash
docker run -it --rm \
  -v /volume1/CrashPlan/var/crashplan:/var/crashplan \
  -v /volume1/Backup:/volume1/Backup:ro \
  jrcs/crashplan:dev true
```

and send me the output ?

**Comment by jk0** [comment]
Would you mind if I took a look at the Dockerfile for this before running it?

**Comment by JrCs** [comment]
This version only add some logs to the output and don't start crashplan

**Comment by jk0** [comment]
```
Before _Link
ls: cannot access '/usr/local/crashplan/cache': No such file or directory
drwxrwxrwx 3 root root    4096 Oct 21 04:46 /var/crashplan/cache/42
-rwxrwxrwx 1 root root     324 Oct 21 04:31 /var/crashplan/cache/cpft1_42
-rwxrwxrwx 1 root root    1854 Oct 21 04:47 /var/crashplan/cache/cpft1_42i
-rwxrwxrwx 1 root root    2110 Oct 21 04:47 /var/crashplan/cache/cpft1_42x
-rwxrwxrwx 1 root root 1165698 Oct 21 04:31 /var/crashplan/cache/cpgft1
-rwxrwxrwx 1 root root  467929 Oct 21 04:47 /var/crashplan/cache/cpgft1i
-rwxrwxrwx 1 root root  558897 Oct 21 04:47 /var/crashplan/cache/cpgft1x
-rwxrwxrwx 1 root root     745 Oct 21 04:31 /var/crashplan/cache/cpss1
After _Link
lrwxrwxrwx 1 root root 20 Oct 31 16:39 /usr/local/crashplan/cache -> /var/crashplan/cache
drwxrwxrwx 3 root root    4096 Oct 21 04:46 /usr/local/crashplan/cache/42
-rwxrwxrwx 1 root root     324 Oct 21 04:31 /usr/local/crashplan/cache/cpft1_42
-rwxrwxrwx 1 root root    1854 Oct 21 04:47 /usr/local/crashplan/cache/cpft1_42i
-rwxrwxrwx 1 root root    2110 Oct 21 04:47 /usr/local/crashplan/cache/cpft1_42x
-rwxrwxrwx 1 root root 1165698 Oct 21 04:31 /usr/local/crashplan/cache/cpgft1
-rwxrwxrwx 1 root root  467929 Oct 21 04:47 /usr/local/crashplan/cache/cpgft1i
-rwxrwxrwx 1 root root  558897 Oct 21 04:47 /usr/local/crashplan/cache/cpgft1x
-rwxrwxrwx 1 root root     745 Oct 21 04:31 /usr/local/crashplan/cache/cpss1
Configuring CrashPlan to listen on public interface 0.0.0.0:4242
-rw-r--r-- 1 root root       4 Oct 31 16:30 /usr/local/crashplan/CrashPlanEngine.pid
-rw-rw-r-- 1 root root 7639158 Oct 31 16:30 /usr/local/crashplan/app.asar
drwxrwxr-x 2 root root    4096 Oct 31 16:39 /usr/local/crashplan/bin
lrwxrwxrwx 1 root root      20 Oct 31 16:39 /usr/local/crashplan/cache -> /var/crashplan/cache
lrwxrwxrwx 1 root root      19 Oct 31 16:39 /usr/local/crashplan/conf -> /var/crashplan/conf
drwxrwxr-x 2 root root    4096 Oct 31 16:30 /usr/local/crashplan/doc
-rw-r--r-- 1 root root     428 Oct 31 16:30 /usr/local/crashplan/install.vars
drwxr-xr-x 5 root root    4096 Oct 31 16:30 /usr/local/crashplan/jre
lrwxrwxrwx 1 root root      19 Oct 31 16:39 /usr/local/crashplan/lang -> /var/crashplan/lang
lrwxrwxrwx 1 root root      18 Oct 31 16:39 /usr/local/crashplan/lib -> /var/crashplan/lib
-rw-rw-r-- 1 root root   11854 Oct 31 16:30 /usr/local/crashplan/libc42archive.so
-rw-rw-r-- 1 root root   13060 Oct 31 16:30 /usr/local/crashplan/libc42archive64.so
-rw-rw-r-- 1 root root   24756 Oct 31 16:30 /usr/local/crashplan/libjniwrap.so
-rw-rw-r-- 1 root root   48344 Oct 31 16:30 /usr/local/crashplan/libjniwrap64.so
-rw-rw-r-- 1 root root  257693 Oct 31 16:30 /usr/local/crashplan/libjtux.so
-rw-rw-r-- 1 root root  287934 Oct 31 16:30 /usr/local/crashplan/libjtux64.so
-rw-rw-r-- 1 root root  403970 Oct 31 16:30 /usr/local/crashplan/libleveldb.so
-rw-rw-r-- 1 root root  427599 Oct 31 16:30 /usr/local/crashplan/libleveldb64.so
-rw-rw-r-- 1 root root    7346 Oct 31 16:30 /usr/local/crashplan/libmd5.so
-rw-rw-r-- 1 root root    8417 Oct 31 16:30 /usr/local/crashplan/libmd564.so
lrwxrwxrwx 1 root root      18 Oct 31 16:39 /usr/local/crashplan/log -> /var/crashplan/log
drwxrwxr-x 3 root root    4096 Oct 31 16:30 /usr/local/crashplan/skin
drwxrwxr-x 3 root root    4096 Oct 31 16:30 /usr/local/crashplan/upgrade
```

**Comment by JrCs** [comment]
So it works as expected:
/usr/local/crashplan/cache is a link to /var/crashplan/cache
and your /var/crashplan/cache directory contain the cache files.
It must works without re-synchronization.
What i see is that your cache is from Oct 21. Is it normal as we are the Oct 31 ?

**Comment by jk0** [comment]
Oct 21st is the last time I restarted the container. If I were to restart it now, the cache would get wiped and the block sync would be restarted.

**Comment by jk0** [comment]
As far as I can tell, when the block sync completes, the results don't get copied to `/var/crashplan/cache`, but only to `/usr/local/crashplan/cache` and when it's restarted, the old/outdated cache in `/var/crashplan/cache` overwrites `/usr/local/crashplan/cache`.

**Comment by jk0** [comment]
Check this out:

```
bash-4.3# ls -lh /var/crashplan/cache/
total 2.2M
drwxrwxrwx 3 root root 4.0K Oct 21 04:46 42
-rwxrwxrwx 1 root root  324 Oct 21 04:31 cpft1_42
-rwxrwxrwx 1 root root 1.9K Oct 21 04:47 cpft1_42i
-rwxrwxrwx 1 root root 2.1K Oct 21 04:47 cpft1_42x
-rwxrwxrwx 1 root root 1.2M Oct 21 04:31 cpgft1
-rwxrwxrwx 1 root root 457K Oct 21 04:47 cpgft1i
-rwxrwxrwx 1 root root 546K Oct 21 04:47 cpgft1x
-rwxrwxrwx 1 root root  745 Oct 21 04:31 cpss1
bash-4.3# ls -lh /usr/local/crashplan/cache/
total 2.2M
drwxr-xr-x 3 root root 4.0K Oct 26 22:39 42
-rw-r--r-- 1 root root   12 Oct 31 03:00 cpft1_42
-rw-r--r-- 1 root root   44 Oct 31 03:00 cpft1_42i
-rw-r--r-- 1 root root   44 Oct 31 03:00 cpft1_42x
-rw-r--r-- 1 root root 1.2M Oct 31 03:01 cpgft1
-rw-r--r-- 1 root root 458K Oct 31 03:01 cpgft1i
-rw-r--r-- 1 root root 547K Oct 31 03:01 cpgft1x
-rw-r--r-- 1 root root  745 Oct 31 03:01 cpss1
bash-4.3#
```

**Comment by jk0** [comment]
The updated/correct cache is in `/usr/local/crashplan/cache` - the directories contain different data.

**Comment by JrCs** [comment]
/urs/local/crashplan/cache is a link to /var/crashplan/cache.
So everything that is write to /usr/local/crashlan/cache is write effectively to /var/crashplan/cache.

Perhaps it the standard behavior for crashplan: it resynchronize the cache if it's too old.
Can you restart it. Wait to resynchronize. The restart it another time and see if it resynchronize ?

**Comment by JrCs** [comment]
Check that /usr/local/crashplan/cache is a link.

**Comment by jk0** [comment]
Doesn't appear to be a link:

```
drwxr-xr-x 3 root root     4096 Oct 31 03:00 cache
```

**Comment by jk0** [comment]
I think we found the problem. :)

**Comment by JrCs** [comment]
Try running with this:

``` bash
docker run -d \
  --name CrashPlan \
  -h $HOSTNAME \
  -p 4242:4242 -p 4243:4243 \
  -v /volume1/CrashPlan/var/crashplan:/var/crashplan \
  -v /volume1/Backup:/volume1/Backup:ro \
  jrcs/crashplan:dev sleep 300
```

Then enter into the container and check if /usr/local/crashplan/cache is a link (it must be a link)
if not do:

``` bash
rmdir /usr/local/crashplan/cache
ln -sf /var/crashplan/cache /usr/local/crashplan/cache
ls -ld /usr/local/crashplan/cache
```

**Comment by jk0** [comment]
It is indeed a link now.

**Comment by JrCs** [comment]
Remove the sleep 300 and check if it works

**Comment by jk0** [comment]
Yep, still works.

**Comment by JrCs** [comment]
Oo so you have un old image.
Do you have make a docker pull jrcs/crashplan:latest before your docker run ?
You can check the docker image age with the docker images command

**Comment by jk0** [comment]
I have the latest image:

```
root@NAS:~# docker pull jrcs/crashplan:latest
latest: Pulling from jrcs/crashplan
Digest: sha256:9ccb28da35c9b8eb155300b76efeb0f79eaca66fbb53d46d8f98b5267d6e130f
Status: Image is up to date for jrcs/crashplan:latest
```

**Comment by JrCs** [comment]
And no resynchronisation with the dev version ?

**Comment by jk0** [comment]
Yeah, it is resyncing, but it looks like the link is still in place. I wonder if the link gets destroyed when the sync completes and tries to write the cache to disk?

**Comment by JrCs** [comment]
Perhaps if the cache is too old, crashplan remove the /usr/local/crashplan/cache directory (the link in our case).
What you can do to test this is to remove the content of your `/volume1/CrashPlan/var/crashplan/cache`

**Comment by jk0** [comment]
I've tested it by restarting the container as soon as the sync and backups are complete. Same result every time. I'll try wiping that directory and report back.

**Comment by jk0** [comment]
I've wiped `/var/crashplan/cache` and restarted the container. The block sync is running and will take several hours to complete. Here is the current status of the cache directories:

```
bash-4.3# ls -la /var/crashplan/cache/
total 4304
drwxrwxrwx 3 root root    4096 Oct 31 17:12 .
drwxrwxrwx 9 root root    4096 Oct 21 04:31 ..
drwxrwxrwx 3 root root    4096 Oct 31 17:12 42
-rwxrwxrwx 1 root root 1166969 Oct 31 17:12 cpft1_42
-rwxrwxrwx 1 root root  469739 Oct 31 17:12 cpft1_42i
-rwxrwxrwx 1 root root  554765 Oct 31 17:12 cpft1_42x
-rwxrwxrwx 1 root root 1166969 Oct 31 17:12 cpgft1
-rwxrwxrwx 1 root root  469739 Oct 31 17:12 cpgft1i
-rwxrwxrwx 1 root root  554765 Oct 31 17:12 cpgft1x
-rwxrwxrwx 1 root root     745 Oct 31 17:12 cpss1
bash-4.3# ls -la /usr/local/crashplan/cache
lrwxrwxrwx 1 root root 20 Oct 31 17:12 /usr/local/crashplan/cache -> /var/crashplan/cache
bash-4.3# ls -la /usr/local/crashplan/cache/
total 4304
drwxrwxrwx 3 root root    4096 Oct 31 17:12 .
drwxrwxrwx 9 root root    4096 Oct 21 04:31 ..
drwxrwxrwx 3 root root    4096 Oct 31 17:12 42
-rwxrwxrwx 1 root root 1166969 Oct 31 17:12 cpft1_42
-rwxrwxrwx 1 root root  469739 Oct 31 17:12 cpft1_42i
-rwxrwxrwx 1 root root  554765 Oct 31 17:12 cpft1_42x
-rwxrwxrwx 1 root root 1166969 Oct 31 17:12 cpgft1
-rwxrwxrwx 1 root root  469739 Oct 31 17:12 cpgft1i
-rwxrwxrwx 1 root root  554765 Oct 31 17:12 cpgft1x
-rwxrwxrwx 1 root root     745 Oct 31 17:12 cpss1
bash-4.3#
```

**Comment by JrCs** [comment]
So it's the file are the same.
I think we have discover a crashplan **feature** !

**Comment by jk0** [comment]
I'll report back with the status of the directories when the sync completes.

**Comment by jk0** [comment]
It looks like the cache persisted after the restart. Now I am completely lost! :)

Unless someone else can confirm this behavior, consider this case closed?

**Comment by JrCs** [comment]
So it confirm that an old cache will be delete by crashplan and the directory mount by the container will be never update anymore.

**Comment by jk0** [comment]
Yep -- after I manually deleted the old cache in `/var/crashplan/cache` it (for some reason) setup the link properly after I restarted the process.

**Comment by jk0** [comment]
UPDATE: It looks like the `/usr/local/crashplan/cache` link gets wipe after an upgrade. This explains why I was seeing this in the first place.

// cc @JrCs

**Comment by jk0** [comment]
And now for some reason, after the upgrade, the link keeps getting destroy when the block sync starts.

**Comment by JrCs** [comment]
So i need to find a solution to not use a link for the cache directory.

**Comment by jk0** [comment]
It looks like we can modify the `cachePath` setting in `/usr/local/crashplan/conf/my.service.xml` -- but I wonder how often that file can get overwritten with updates too?

**Comment by jk0** [comment]
Perhaps using the same linking strategy with that XML file would work?

**Comment by jk0** [comment]
...while somehow figuring out the diff (if any, while ignoring any changes to `cachePath`) after updates?

**Comment by JrCs** [comment]
@jk0 can you test the new jrcs/crashplan:dev image ?

**Comment by jk0** [comment]
Would you mind showing me a diff?

**Comment by JrCs** [comment]
I have remake the container.
See if it works: doing automatic upgrades (if needed) and if it don't resynchronize.

**Comment by jk0** [comment]
No offense, I'm just curious to see what's going in the image.

**Comment by JrCs** [comment]
I have push my modifications in the dev branch if you need to look.

**Comment by jk0** [comment]
Okay, thanks. Trying now.

**Comment by jk0** [comment]
Getting:

```
STACKTRACE:: java.io.FileNotFoundException: /var/lib/crashplan/.ui_info (No such file or directory)
    at java.io.FileInputStream.open0(Native Method)
    at java.io.FileInputStream.open(FileInputStream.java:195)
    at java.io.FileInputStream.<init>(FileInputStream.java:138)
    at java.io.FileReader.<init>(FileReader.java:72)
    at com.code42.io.FileUtility.readTextFile(FileUtility.java:1650)
    at com.backup42.service.ui.UIInfoUtility.getUIConnectionDetails(UIInfoUtility.java:50)
    at com.backup42.service.ui.UIController.receiveMessage(UIController.java:1153)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.code42.messaging.MessageReceiverProxy.receiveMessage(MessageReceiverProxy.java:153)
    at com.code42.messaging.SessionImpl.receiveMessage(SessionImpl.java:479)
    at com.code42.messaging.network.nio.MessageQueue$MessageWorker.handle(MessageQueue.java:166)
    at com.code42.messaging.network.nio.MessageQueue$MessageWorker.handle(MessageQueue.java:86)
    at com.code42.queue.QueueWorker.run(QueueWorker.java:48)
    at com.code42.messaging.network.nio.MessageQueue$MessageWorker.run(MessageQueue.java:132)
```

**Comment by JrCs** [comment]
/var/lib/crashplan must be a link to /var/crashplan/id 
Strange can you connect to the GUI ?

**Comment by jk0** [comment]
Nope, that's what happens when I try to connect.

**Comment by JrCs** [comment]
Check if /var/lib/crashplan is a link to /var/crashplan/id.
/var/crashplan/id must contain 2 files:

```
.ui_info
.identity
```

**Comment by jk0** [comment]
```
bash-4.3# ls -la /var/lib/crashplan/id
ls: cannot access '/var/lib/crashplan/id': No such file or directory
bash-4.3# ls -la /var/lib/crashplan/id/
ls: cannot access '/var/lib/crashplan/id/': No such file or directory
```

**Comment by jk0** [comment]
```
bash-4.3# ls -la /var/lib/crashplan
lrwxrwxrwx 1 root root 17 Nov  5 12:23 /var/lib/crashplan -> /var/crashplan/id
```

**Comment by JrCs** [comment]
So why don't you have the .ui_info ?
It must be there before

**Comment by jk0** [comment]
Something wiped out the directory/link

**Comment by JrCs** [comment]
can you recreate the .ui_info file ?

**Comment by jk0** [comment]
I've gotta do it later man. I've been up all night working. Sorry but I just can't focus on it at the moment ;\

**Comment by jk0** [comment]
I could very well be overlooking something and I don't want to go down an unnecessary rabbit hole

**Comment by JrCs** [comment]
OK, sorry it's afternoon here in france

**Comment by jk0** [comment]
No worries -- I totally understand. This one is on me :)

**Comment by jk0** [comment]
I want to make sure I'm giving you good feedback, but I'm drained at the moment so I'll come back later. Thanks for looking into it with me

**Comment by JrCs** [comment]
@jk0 Is it working now ?

**Comment by JrCs** [comment]
Closing issue. No more informations.
