### ISSUE TITLE
Crashplan Shutting Down Then Won't Allow Restart

### ISSUE THREAD

**Issue by mweinhauer** [JrCs/docker-crashplan#40]
[03.10.17 07:16:26.763 ERROR main           com.backup42.service.CPService] Cannot bind to 192.168.1.243:4243, java.net.BindException: Cannot assign requested address                                                                                                                                                    
STACKTRACE:: java.net.BindException: Cannot assign requested address         

It throws this error after running fine for a few hours. It's like it's holding on to the port assignment and won't release it, even if I stop and restart the container.  I don't want to deploy a new container because then I have to adopt the old one and Crashplan goes through its whole block syncing exercise that takes hours! 

Any ideas? Thanks!

**Comment by mweinhauer** [comment]
Anyone else have this problem? I really want this to work but it keeps dying on me. I have 8GB of RAM on my NAS so it shouldn't be resources, and the container is set to allow the use of most of that if needed.

**Comment by mweinhauer** [comment]
It crashes right after it finishes syncing and doing the block scan.  Once it tries to shift to backing up new files it crashes with the error above.

**Comment by mweinhauer** [comment]
It seems to want to communicate on 4242 and it's failing on that - can't bind.

**Comment by mweinhauer** [comment]
any ideas anyone? Please?

**Comment by johnny2678** [comment]
I think we're having the same issue - not sure.  But everything was running fine until 3 days ago, then
```
   main         e42.messaging.peer.PeerConnector] PC:: Cannot assign requested address, location=[756219371864818002@192.168.X.X:4242], layer=PeerLayer@362237774[756219371864818002@192.168.X.X:4242], com.code42.exception.DebugException: Cannot assign requested address, location=[756219371864818002@192.168.X.X:4242], layer=PeerLayer@362237774[756219371864818002@192.168.X.X:4242]
STACKTRACE:: com.code42.exception.DebugException: Cannot assign requested address, location=[756219371864818002@192.168.X.X:4242], layer=PeerLayer@362237774[756219371864818002@192.168.X.X:4242]
	at com.code42.messaging.peer.PeerConnector.listen(PeerConnector.java:226)
	at com.code42.messaging.peer.PeerGroup.listen(PeerGroup.java:660)
	at com.code42.messaging.peer.PeerLayer.listen(PeerLayer.java:464)
	at com.backup42.service.peer.PeerController.listen(PeerController.java:400)
	at com.backup42.common.peer.PeerAgentController.start(PeerAgentController.java:107)
	at com.backup42.service.peer.PeerController.start(PeerController.java:281)
	at com.backup42.service.CPService.startPeerLayer(CPService.java:2940)
```

**Comment by johnny2678** [comment]
More from the logs - not sure if it's related:
```
[03.23.17 13:44:28.752 WARN  DefaultGroup .code42.messaging.peer.PeerGroup] PG::DefaultGroup PeerException attempting to connect. RemotePeer-[guid=4200, SERVER]; PeerConnectionState-[state=CONNECTING, mode=PRIVATE, currentAddressIndex=0, layer=2/2(Peer::NIO), connecting=2017-03-23T13:44:28:750, connected=0, disconnected=2017-03-23T13:42:01:533, attempts=4, connectActivity=2017-03-23T13:44:28:750, keepAliveSent=0, minRetry=28759, reconnectable, location=central.crashplan.com:443, transportPbK=X509.checksum(be4b2a71961d23dabb77ea3851a2fc8d), transportPbKRequestable=true, public=central.crashplan.com:4282]; Session-null e=com.code42.peer.exception.PeerException: IOExcepton opening remote session. guid=4200, remoteLocation=[[4200@central.crashplan.com:443(server)], transportPbK=X509.checksum(be4b2a71961d23dabb77ea3851a2fc8d)], timeout=30000, java.io.IOException: Unexpected Exception in connect() for remoteAddress=central.crashplan.com:443, java.nio.channels.UnresolvedAddressException
[03.23.17 13:44:30.759 WARN  DefaultGroup .code42.messaging.peer.PeerGroup] PG::DefaultGroup PeerException attempting to connect. RemotePeer-[guid=4200, SERVER]; PeerConnectionState-[state=CONNECTING, mode=PUBLIC, currentAddressIndex=0, layer=2/2(Peer::NIO), connecting=2017-03-23T13:44:30:758, connected=0, disconnected=2017-03-23T13:44:28:752, attempts=4, connectActivity=2017-03-23T13:44:30:758, keepAliveSent=0, minRetry=28759, reconnectable, location=central.crashplan.com:443, transportPbK=X509.checksum(be4b2a71961d23dabb77ea3851a2fc8d), transportPbKRequestable=true, public=central.crashplan.com:4282]; Session-null e=com.code42.peer.exception.PeerException: IOExcepton opening remote session. guid=4200, remoteLocation=[4200@central.crashplan.com:4282], timeout=30000, java.io.IOException: Unexpected Exception in connect() for remoteAddress=central.crashplan.com:4282, java.nio.channels.UnresolvedAddressException
[03.23.17 13:45:05.875 INFO  e-listen-1-1 abre.SabrePendingChannelListener] SABRE::Channel connect failed for guid 42, cause=java.net.UnknownHostException: awd-sea.crashplan.com
[03.23.17 13:45:05.876 INFO  e-listen-1-1 .network.sabre.SabreNetworkLayer] SABRE:: Cancelling connect to 42 at awd-sea.crashplan.com:443. connectFuture.isDone=true, channel=[id: 0x30abb998]
[03.23.17 13:45:07.890 INFO  e-listen-1-2 abre.SabrePendingChannelListener] SABRE::Channel connect failed for guid 42, cause=java.net.UnknownHostException: awd-sea.crashplan.com
[03.23.17 13:45:07.890 INFO  e-listen-1-2 .network.sabre.SabreNetworkLayer] SABRE:: Cancelling connect to 42 at awd-sea.crashplan.com:4287. connectFuture.isDone=true, channel=[id: 0x91305ee2]
[03.23.17 13:47:15.012 INFO  e-listen-1-1 abre.SabrePendingChannelListener] SABRE::Channel connect failed for guid 4200, cause=java.net.UnknownHostException: central.crashplan.com
[03.23.17 13:47:15.012 INFO  e-listen-1-1 .network.sabre.SabreNetworkLayer] SABRE:: Cancelling connect to 4200 at central.crashplan.com:443. connectFuture.isDone=true, channel=[id: 0x6c7a26b4]
[03.23.17 13:47:17.018 INFO  e-listen-1-2 abre.SabrePendingChannelListener] SABRE::Channel connect failed for guid 4200, cause=java.net.UnknownHostException: central.crashplan.com
[03.23.17 13:47:17.018 INFO  e-listen-1-2 .network.sabre.SabreNetworkLayer] SABRE:: Cancelling connect to 4200 at central.crashplan.com:4287. connectFuture.isDone=true, channel=[id: 0xa0663306]
```

**Comment by johnny2678** [comment]
seems to be fixed by using `--net=host` instead of specifying ports like I was doing: `-p 4242:4242 -p 4243:4243`

This was working up until 3 days ago so I'm moderately curious what changed, but I can live with `--net=host` for now.

**Comment by mweinhauer** [comment]
yes that looks identical.  Weird!  So do I just spawn the container and substitute the net=host string for the -p 4242:4242 -p 4243:4243 parameters?  Thanks!

**Comment by johnny2678** [comment]
yep, that's what I did

**Comment by mweinhauer** [comment]
I have a "-publish 4242-4243:4242-4243 parameter, not just "-p".  Do I need two "- -" like you have there? Sorry I'm struggling w the syntax and want to get it right.  So is it like this:

docker run -d --name crashplan -e TZ=Etc/GMT+8 --publish net=host --volume /share/CACHEDEV1_DATA/Containers/CrashPlan:/var/crashplan --volume /share/CACHEDEV1_DATA:/share/CACHEDEV1_DATA jrcs/crashplan

Thanks -Mike

**Comment by johnny2678** [comment]
remove `--publish` altogether along with the port numbers and replace with `--net=host` (yes, 
2 hyphens)

**Comment by mweinhauer** [comment]
Running - fingers crossed. Big test will be once it finishes syncing block info and tries to start the actual backup.  Thank you!
