### ISSUE TITLE
Container randomly freezing (goes silent, no more activity, but process is alive)

### ISSUE THREAD

**Issue by hheimbuerger** [JrCs/docker-crashplan#6]
For me, the container just stops doing anything randomly at some point. Does anybody else have this and/or knows a solution?

Right now, I've had it running for seven days and five days ago it just stopped logging anything stdout and `service.log.0`, and it also stopped doing anything backup-wise. The main process is still alive, so Docker hasn't restarted the container. It's just not doing anything.

It had updated to 4.6.0 a couple days a while earlier (long enough before the freeze that I don't suspect a connection).

I don't find anything suspicious in the log files. There's a lot of stacktraces (`IllegalArgumentException: Peer already existed, cannot add`), but they always occur every minute, even while it's running well. Here's the very last lines before it just went silent.

```
[04.03.16 10:24:43.127 WARN  on-825222751 2.messaging.peer.NATContinuation] [NATContinuation[736404681217745414](0):733556053290072213<->733351749112369151][active/A_INV_SENT] INVITE timeout, STOP
[04.03.16 10:24:43.329 WARN  on-825222751 de42.messaging.peer.NATConnector] [NATContinuation[736404681217745414](0):733556053290072213<->733351749112369151][active/STOP]  RP:: TRAVERSAL FAILURE for com.code42.messaging.peer.NATConnector@7c3ce6ef
[04.03.16 10:24:54.915 INFO  ystemWatcher ode42.messaging.nio.MessageQueue] MW:: STATS:UI : numWorkers=2, queue.size=0, MessageQueueStats[num=0, numSinceLast=0, handling=Counter[count = 0, rate = 0.00, rollingRate = 0.00], waiting=Counter[count = 0, rate = 0.00, rollingRate = 0.00], workload=1.000]
[04.03.16 10:25:36.945 INFO  DefaultGroup .code42.messaging.peer.PeerGroup] PG::DefaultGroup DONE Managing connected remote peers. numConnected=7, numFailedConnectedCheck=0, duration(ms)=35
[04.03.16 10:25:39.300 INFO  erTimeoutWrk e42.messaging.peer.PeerConnector] PC:: Cancelling connection attempt due to timeout - pending connection=PendingConnection[timeout(ms) = 10000, startTime = Sun Apr 03 10:25:25 GMT 2016, remotePeer = RemotePeer-[guid=733351749112369151, state=CONNECTING, mode=PRIVATE, location=192.168.178.56:4242, public=79.247.139.110:0, transportPbK=X509.checksum(dfb2987cb569a2e55152753fa25ab089), transportPbKRequestable=false, connecting=2016-04-03T10:25:25:139, connected=0, disconnected=2016-04-03T10:24:43:329, attempts=2, connectActivity=2016-04-03T10:25:25:139, keepAliveSent=0, minRetry=29648, retryDelay=0, reflector=na, #nat=1, session=null], sessionData = MessageConnection[ sessionInfo=Session[ null], readBuffer=com.code42.messaging.nio.MessageConnection$MessageBuffer@38c687d0, maxBufferSize = 65536, currentSize = 0, enqueued = false, #items = 0, Connection[481292855, state=0, context = Context@231989070[null->nullconnectionState=0], SendBufferQueue[closed=false, queueSize=0, maxSize=1310720, enqueueTimeout=60000, numItems=0, waitingCount=0, waitingPriorityCount=0, items.size()=0, priorityItems.size()=0, lastEnqueueTS=0]]]]
[04.03.16 10:25:49.442 INFO  erTimeoutWrk e42.messaging.peer.PeerConnector] PC:: Cancelling connection attempt due to timeout - pending connection=PendingConnection[timeout(ms) = 5000, startTime = Sun Apr 03 10:25:39 GMT 2016, remotePeer = RemotePeer-[guid=733351749112369151, state=CONNECTING, mode=PRIVATE, location=192.168.178.56:4242, public=79.247.139.110:0, transportPbK=X509.checksum(dfb2987cb569a2e55152753fa25ab089), transportPbKRequestable=false, connecting=2016-04-03T10:25:39:430, connected=0, disconnected=2016-04-03T10:25:39:427, attempts=1, connectActivity=2016-04-03T10:25:39:430, keepAliveSent=0, minRetry=29648, retryDelay=0, reflector=na, #nat=1, session=null], sessionData = MessageConnection[ sessionInfo=Session[ null], readBuffer=com.code42.messaging.nio.MessageConnection$MessageBuffer@6137fca8, maxBufferSize = 65536, currentSize = 0, enqueued = false, #items = 0, Connection[1841504089, state=0, context = Context@245266076[null->nullconnectionState=0], SendBufferQueue[closed=false, queueSize=0, maxSize=1310720, enqueueTimeout=60000, numItems=0, waitingCount=0, waitingPriorityCount=0, items.size()=0, priorityItems.size()=0, lastEnqueueTS=0]]]]
[04.03.16 10:25:50.725 WARN  MQ-Peer-1    2.messaging.MessageReceiverProxy] MessageReceiverProxy: InvocationTargetException receiving message=type=com.code42.peer.message.NATInviteMessage, contents=NATInviteMessage[736326220872622598] [734415399723664691@217.51.136.219:53061], session=Session[id=736326220872622598, closed=false, isAcceptor=false, remoteIdentity=ENDPOINT, completedAuth=true, lat=2016-04-03T10:25:50:716, lrt=2016-04-03T10:25:50:716, lwt=2016-04-03T10:25:36:934, #pending=0, enqueued=true, local=172.17.0.7:50856, remote=216.17.8.3:443, usingProtoHeaders=true, usingEncryptedHeaders=true, WAN], e=java.lang.reflect.InvocationTargetException, cause=java.lang.IllegalArgumentException: Peer already existed, cannot add. PeerLocation=[[734415399723664691@217.51.136.219:53061]], java.lang.IllegalArgumentException: Peer already existed, cannot add. PeerLocation=[[734415399723664691@217.51.136.219:53061]]
STACKTRACE:: java.lang.IllegalArgumentException: Peer already existed, cannot add. PeerLocation=[[734415399723664691@217.51.136.219:53061]]
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
    at com.code42.messaging.peer.PeerGroup.addPeerFromLocation(PeerGroup.java:683)
    at com.code42.messaging.peer.NATAgent.receiveMessage(NATAgent.java:94)
    at sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.code42.messaging.MessageReceiverProxy.receiveMessage(MessageReceiverProxy.java:149)
    at com.code42.messaging.Session.receiveMessage(Session.java:379)
    at com.code42.messaging.nio.MessageQueue$MessageWorker.handle(MessageQueue.java:161)
    at com.code42.messaging.nio.MessageQueue$MessageWorker.handle(MessageQueue.java:80)
    at com.code42.queue.QueueWorker.run(QueueWorker.java:47)
    at com.code42.messaging.nio.MessageQueue$MessageWorker.run(MessageQueue.java:126)

[04.03.16 10:26:23.744 WARN  n-1841228017 2.messaging.peer.NATContinuation] [NATContinuation[736404850046870022](0):733556053290072213<->734415399723664691][active/A_INV_SENT] INVITE timeout, STOP
[04.03.16 10:26:23.950 WARN  n-1841228017 de42.messaging.peer.NATConnector] [NATContinuation[736404850046870022](0):733556053290072213<->734415399723664691][active/STOP]  RP:: TRAVERSAL FAILURE for com.code42.messaging.peer.NATConnector@3010c4e2
[04.03.16 10:27:19.562 INFO  erTimeoutWrk e42.messaging.peer.PeerConnector] PC:: Cancelling connection attempt due to timeout - pending connection=PendingConnection[timeout(ms) = 10000, startTime = Sun Apr 03 10:27:05 GMT 2016, remotePeer = RemotePeer-[guid=734415399723664691, state=CONNECTING, mode=PRIVATE, location=192.168.1.4:4242, public=217.51.136.219:0, transportPbK=X509.checksum(895e4250e002a5f9aedf1304f7226991), transportPbKRequestable=false, connecting=2016-04-03T10:27:05:083, connected=0, disconnected=2016-04-03T10:26:23:951, attempts=2, connectActivity=2016-04-03T10:27:05:083, keepAliveSent=0, minRetry=29930, retryDelay=0, reflector=na, #nat=1, session=null], sessionData = MessageConnection[ sessionInfo=Session[ null], readBuffer=com.code42.messaging.nio.MessageConnection$MessageBuffer@1da4e1ae, maxBufferSize = 65536, currentSize = 0, enqueued = false, #items = 0, Connection[1126734862, state=0, context = Context@920939237[null->nullconnectionState=0], SendBufferQueue[closed=false, queueSize=0, maxSize=1310720, enqueueTimeout=60000, numItems=0, waitingCount=0, waitingPriorityCount=0, items.size()=0, priorityItems.size()=0, lastEnqueueTS=0]]]]
[04.03.16 10:27:29.667 INFO  erTimeoutWrk e42.messaging.peer.PeerConnector] PC:: Cancelling connection attempt due to timeout - pending connection=PendingConnection[timeout(ms) = 5000, startTime = Sun Apr 03 10:27:19 GMT 2016, remotePeer = RemotePeer-[guid=734415399723664691, state=CONNECTING, mode=PRIVATE, location=192.168.1.4:4242, public=217.51.136.219:0, transportPbK=X509.checksum(895e4250e002a5f9aedf1304f7226991), transportPbKRequestable=false, connecting=2016-04-03T10:27:19:667, connected=0, disconnected=2016-04-03T10:27:19:667, attempts=1, connectActivity=2016-04-03T10:27:19:667, keepAliveSent=0, minRetry=29930, retryDelay=0, reflector=na, #nat=1, session=null], sessionData = MessageConnection[ sessionInfo=Session[ null], readBuffer=com.code42.messaging.nio.MessageConnection$MessageBuffer@4bb3d033, maxBufferSize = 65536, currentSize = 0, enqueued = false, #items = 0, Connection[1906368890, state=0, context = Context@1995430828[null->nullconnectionState=0], SendBufferQueue[closed=false, queueSize=0, maxSize=1310720, enqueueTimeout=60000, numItems=0, waitingCount=0, waitingPriorityCount=0, items.size()=0, priorityItems.size()=0, lastEnqueueTS=0]]]]
[04.03.16 10:27:39.340 WARN  MQ-Peer-1    2.messaging.MessageReceiverProxy] MessageReceiverProxy: InvocationTargetException receiving message=type=com.code42.peer.message.NATInviteMessage, contents=NATInviteMessage[736326220872622598] [733351749112369151@79.247.139.110:52973], session=Session[id=736326220872622598, closed=false, isAcceptor=false, remoteIdentity=ENDPOINT, completedAuth=true, lat=2016-04-03T10:27:39:336, lrt=2016-04-03T10:27:39:336, lwt=2016-04-03T10:26:36:711, #pending=0, enqueued=true, local=172.17.0.7:50856, remote=216.17.8.3:443, usingProtoHeaders=true, usingEncryptedHeaders=true, WAN], e=java.lang.reflect.InvocationTargetException, cause=java.lang.IllegalArgumentException: Peer already existed, cannot add. PeerLocation=[[733351749112369151@79.247.139.110:52973]], java.lang.IllegalArgumentException: Peer already existed, cannot add. PeerLocation=[[733351749112369151@79.247.139.110:52973]]
STACKTRACE:: java.lang.IllegalArgumentException: Peer already existed, cannot add. PeerLocation=[[733351749112369151@79.247.139.110:52973]]
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
    at com.code42.messaging.peer.PeerGroup.addPeerFromLocation(PeerGroup.java:683)
    at com.code42.messaging.peer.NATAgent.receiveMessage(NATAgent.java:94)
    at sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.code42.messaging.MessageReceiverProxy.receiveMessage(MessageReceiverProxy.java:149)
    at com.code42.messaging.Session.receiveMessage(Session.java:379)
    at com.code42.messaging.nio.MessageQueue$MessageWorker.handle(MessageQueue.java:161)
    at com.code42.messaging.nio.MessageQueue$MessageWorker.handle(MessageQueue.java:80)
    at com.code42.queue.QueueWorker.run(QueueWorker.java:47)
    at com.code42.messaging.nio.MessageQueue$MessageWorker.run(MessageQueue.java:126)

[04.03.16 10:28:03.712 WARN  ion-46752562 2.messaging.peer.NATContinuation] [NATContinuation[736405017768698374](0):733556053290072213<->733351749112369151][active/A_INV_SENT] INVITE timeout, STOP
[04.03.16 10:28:03.916 WARN  ion-46752562 de42.messaging.peer.NATConnector] [NATContinuation[736405017768698374](0):733556053290072213<->733351749112369151][active/STOP]  RP:: TRAVERSAL FAILURE for com.code42.messaging.peer.NATConnector@7c3ce6ef
[04.03.16 10:28:55.125 INFO  ystemWatcher ode42.messaging.nio.MessageQueue] MW:: STATS:Peer : numWorkers=4, queue.size=0, MessageQueueStats[num=1199, numSinceLast=2, handling=Counter[count = 4301, rate = 0.10, rollingRate = 0.09], waiting=Counter[count = 188176583, rate = 1810.08, rollingRate = 4211.56], workload=0.000]
[04.03.16 10:28:59.777 INFO  erTimeoutWrk e42.messaging.peer.PeerConnector] PC:: Cancelling connection attempt due to timeout - pending connection=PendingConnection[timeout(ms) = 10000, startTime = Sun Apr 03 10:28:45 GMT 2016, remotePeer = RemotePeer-[guid=733351749112369151, state=CONNECTING, mode=PRIVATE, location=192.168.178.56:4242, public=79.247.139.110:0, transportPbK=X509.checksum(dfb2987cb569a2e55152753fa25ab089), transportPbKRequestable=false, connecting=2016-04-03T10:28:45:001, connected=0, disconnected=2016-04-03T10:28:03:916, attempts=2, connectActivity=2016-04-03T10:28:45:001, keepAliveSent=0, minRetry=29648, retryDelay=0, reflector=na, #nat=1, session=null], sessionData = MessageConnection[ sessionInfo=Session[ null], readBuffer=com.code42.messaging.nio.MessageConnection$MessageBuffer@634924d6, maxBufferSize = 65536, currentSize = 0, enqueued = false, #items = 0, Connection[917394116, state=0, context = Context@1089723994[null->nullconnectionState=0], SendBufferQueue[closed=false, queueSize=0, maxSize=1310720, enqueueTimeout=60000, numItems=0, waitingCount=0, waitingPriorityCount=0, items.size()=0, priorityItems.size()=0, lastEnqueueTS=0]]]]
[04.03.16 10:29:09.885 INFO  erTimeoutWrk e42.messaging.peer.PeerConnector] PC:: Cancelling connection attempt due to timeout - pending connection=PendingConnection[timeout(ms) = 5000, startTime = Sun Apr 03 10:28:59 GMT 2016, remotePeer = RemotePeer-[guid=733351749112369151, state=CONNECTING, mode=PRIVATE, location=192.168.178.56:4242, public=79.247.139.110:0, transportPbK=X509.checksum(dfb2987cb569a2e55152753fa25ab089), transportPbKRequestable=false, connecting=2016-04-03T10:28:59:884, connected=0, disconnected=2016-04-03T10:28:59:884, attempts=1, connectActivity=2016-04-03T10:28:59:884, keepAliveSent=0, minRetry=29648, retryDelay=0, reflector=na, #nat=1, session=null], sessionData = MessageConnection[ sessionInfo=Session[ null], readBuffer=com.code42.messaging.nio.MessageConnection$MessageBuffer@48c95f53, maxBufferSize = 65536, currentSize = 0, enqueued = false, #items = 0, Connection[1653386504, state=0, context = Context@644934639[null->nullconnectionState=0], SendBufferQueue[closed=false, queueSize=0, maxSize=1310720, enqueueTimeout=60000, numItems=0, waitingCount=0, waitingPriorityCount=0, items.size()=0, priorityItems.size()=0, lastEnqueueTS=0]]]]
[04.03.16 10:29:43.662 WARN  on-558619013 2.messaging.peer.NATContinuation] [NATContinuation[736405185406640646](0):733556053290072213<->734415399723664691][active/A_INV_SENT] INVITE timeout, STOP
[04.03.16 10:29:43.870 WARN  on-558619013 de42.messaging.peer.NATConnector] [NATContinuation[736405185406640646](0):733556053290072213<->734415399723664691][active/STOP]  RP:: TRAVERSAL FAILURE for com.code42.messaging.peer.NATConnector@3010c4e2
[04.03.16 10:29:55.130 INFO  ystemWatcher ode42.messaging.nio.MessageQueue] MW:: STATS:UI : numWorkers=2, queue.size=0, MessageQueueStats[num=0, numSinceLast=0, handling=Counter[count = 0, rate = 0.00, rollingRate = 0.00], waiting=Counter[count = 0, rate = 0.00, rollingRate = 0.00], workload=1.000]
```

**Comment by JrCs** [comment]
My crashplan container is working for several months without a glitch.
I using docker 1.10.3 on CoreOS.

**Comment by hheimbuerger** [comment]
@JrCs Do you also get these `java.lang.IllegalArgumentException: Peer already existed, cannot add` on a regular basis? (I don't see a connection, but it's the only starting point I've got.)

I'm running Docker 1.9.1-cs2 (the latest on Docker Cloud).

**Comment by JrCs** [comment]
@hheimbuerger Yes i have the same messages every hour or two.

**Comment by hheimbuerger** [comment]
@jrcs Odd. I filed a ticket with CrashPlan, let's see what they respond. (I expect them to take a few weeks though. My last ticket took more than two weeks until the first response.)

Either way, it's probably not related to my freezing then. I don't really know what else to check. Do you get the `INVITE timeout, STOP` and `TRAVERSAL FAILURE`, too?

**Comment by JrCs** [comment]
I have just ONE message with `INVITE timeout, STOP` and `TRAVERSAL FAILURE` one month ago

**Comment by hheimbuerger** [comment]
@JrCs I've been talking to someone smart at CrashPlan's support line. He said the warnings in the log are all non-concerning. He did make a few recommendations, however:

Do you remember why you're been setting this up with a pre-installed JRE, as opposed to using the one bundled with CrashPlan?

Is there a specific reason to limit the JVM to 512 MiB, when the CrashPlan default is 1024 MiB?

**Comment by JrCs** [comment]
For the JRE i use a java build from Alpine Linux to get a "small" image.
Perhaps i can try to use the one that download during the installation.
For the JVM i have no reason to limit the JVM to 512MiB.
Do you know where i need to change the value ?

**Comment by JrCs** [comment]
I have check and i never change the option of the JVM to limit the memory.
I will recreate a new version with the JRE provide by crashplan.

**Comment by JrCs** [comment]
@hheimbuerger Done ! I have create a new container with the legacy crashplan JRE.
The JVM is limit to 1024 MiB (the default).
I have reduce the image size from 190MiB to 169MiB.

**Comment by hheimbuerger** [comment]
@JrCs Thanks for your work on this! I switched to the new image, I'll let you know how it goes. :)

**Comment by hheimbuerger** [comment]
@JrCs So the right (and so simple, but I didn't think of it!) troubleshooting step would have been to run `dmesg`, which clearly shows that the OS killed the CrashPlan process because it ran out of memory.

The core problem here is that when the CrashPlan Java process crashes (no signals), this doesn't reflect back to the container. It will happily keep running, even though CrashPlan is long gone.

Apart from compatibility with future versions, is there a specific reason you're running CrashPlan as a service in the container?

Right now, this is what I think happens:
[files/crashplan.sh@14](https://github.com/JrCs/docker-crashplan/blob/master/files/crashplan.sh#L14) calls `/etc/init.d/crashplan start`. That is pretty much just a thin alias for `/usr/local/crashplan/bin/CrashPlanEngine start`. That's a longer script which sets a lot of environment variables. But in the end, it runs this:

```
nice -n 19 \
  java $SRV_JAVA_OPTS \
  -classpath $FULL_CP \
  com.backup42.service.CPService \
  > $TARGETDIR/log/engine_output.log \
  2> $TARGETDIR/log/engine_error.log &
```

I'm considering to run this line directly without the trailing `&` (after setting the required envvars), because then I'd have proper dockerized foreground process. If it then crashes, I'll at least see this in Docker and/or can set it up to automatically restart CrashPlan.

**Comment by JrCs** [comment]
There 2 problems. If you do this you will not see the logs with the docker logs command, and i don't know if it will not affect the auto update process.
I will try to find a solution ...

**Comment by hheimbuerger** [comment]
@JrCs I think the first problem could be solved with something like `tee` (see [SO: "How to pipe stdout while keeping it on screen?"](http://stackoverflow.com/q/5677201/6278) and [SO: "How to redirect output to a file and stdout"](http://stackoverflow.com/a/418899/6278)).

I agree that it would make the image much more unstable against changes by CrashPlan, i.e. every time they change something about the way CrashPlan needs to be started, the image needs to be adapted as well. That's unfortunate.

I've done some work on starting the process directly (without the service scripts) [here](https://github.com/hheimbuerger/docker-crashplan/blob/1e610e3c969a4cde52520e52287d9228ffd18898/files/crashplan.sh#L19), but it doesn't work out of the box yet. It's work in process. I managed to run the process directly from the shell, but then got distracted when I figured out that my root issue was lack of memory).

**Comment by noaho** [comment]
Have you guys seen this article on making sure your java max memory matches your backup selection? eg 2GB for 2TB? https://support.code42.com/CrashPlan/4/Troubleshooting/CrashPlan_Closes_Unexpectedly

**Comment by hheimbuerger** [comment]
@NoahO Check my comments, I've already identified lack of memory as the culprit! :p

It's now about something else, namely that when it hits the memory limit, CrashPlan dies, but the Docker container keeps running.

Also, CrashPlan's advice is rather general. I have 380 files in total of 28 MiB to back up, but 512 MiB of ram were not sufficient. Then again, that's also below CrashPlan's official minimum.

**Comment by nunofgs** [comment]
@hheimbuerger: FWIW, I'm having the exact same issue as you, but on a raspberry pi (I used this same Dockerfile but simple switched the base image to an alpine ARM image).

After a few hours it just dies without warning, yet the container itself doesn't die. I can confirm this by _sh-ing_ into the container and verifying that the process is not running.

Have you been able to determine if the culprit is a signal forwarding issue in the `/usr/local/crashplan/bin/CrashPlanEngine` script?

**Comment by hheimbuerger** [comment]
@nunofgs Again, I'm very sure the culprit is lack of memory! Please run `dmesg` right after it disappears, you'll should see the kernel kicking the `java` process out! It looks something like this for me:

```
[4083068.635099] Out of memory: Kill process 23370 (java) score 190 or sacrifice child                                                                          
[4083068.638138] Killed process 23370 (java) total-vm:1894532kB, anon-rss:95200kB, file-rss:0kB
```

If adding more ram is not an option (as probably on the Pi), you might be able to fix this by [setting up a swap file](http://stackoverflow.com/a/31141359/6278). That's what I've done to work around it for now.

All the discussion I've been having here with @JrCs around `/usr/local/crashplan/bin/CrashPlanEngine` was just about trying to find a way to get some more graceful error reporting in that situation.

It will **not** in any way fix the memory issue! Even if this is changed, the CrashPlan process will die/get killed just as quickly, the only difference would be that the container goes down with it!

**Comment by JrCs** [comment]
I will update the image to make the container die if java die.

**Comment by nunofgs** [comment]
@hheimbuerger: agreed, it is indeed a memory issue in my case but when compounded with the fact the container did not die, it took me days until I found my backups weren't running :)

@JrCs: glad to hear, thank you!

**Comment by hheimbuerger** [comment]
@nunofgs Yeah, I agree, I also spent many hours debugging. :(
Then again, I feel slightly stupid now that I didn't just check `dmesg` in the first place. Lesson learned, I guess. :)

**Comment by hheimbuerger** [comment]
@JrCs Any idea on this yet?

I was just considering to reconfigure my logging to only have warnings and errors logged on stdout and the full log only in service.log. But then I realized that this currently isn't possible, because the Docker container isn't actually using the Console logger as stdout, instead it tails the service.log to stdout.

**Comment by JrCs** [comment]
Sorry i don't have time currently. I think the best is to use a supervisor that will kill the container if the java really die (not restart because of an upgrade)

**Comment by haysclark** [comment]
Is this issue just related to Java running in a background process? I ran into a similar issue with another app that would default to running in the background on the host OS.  You would start the server, the container would run until it was idle, then the container would sleep.

Here are my comments in my docker file (again, NOT a Java app):

    # lmgrd -z flag is required to 'Run in foreground.' so that
    # Docker will not start sleeping regardless flags.
    ENTRYPOINT ["lmgrd", "-z"]`

https://hub.docker.com/r/haysclark/adlmflexnetserver/~/dockerfile/

Just a stab in the dark.

**Comment by hheimbuerger** [comment]
@haysclark Can you clarify which issue you're talking about when asking about "this issue"?

If you run multiple processes in a docker container and a non-primary one terminates, then the docker container does not terminate. That's not Java-specific at all, no. But I don't quite see how any of that is related.
